apiVersion: v1
kind: Service #tipe service
metadata:
  namespace: karsajobs-ns #nama namespace yang digunakan
  name: karsajobs-ui-service #nama object
  labels:
    app: karsajobs-ui #label object
spec:
  type: NodePort 
  selector:
    app: karsajobs-ui
  ports:
    - port: 8000
      targetPort: 8000