apiVersion: v1
kind: Secret #tipe oject
metadata:
  name: mongo-credentials #nama object
  namespace: karsajobs-ns #nama namespace
type: Opaque
data:
  MONGO_ROOT_USERNAME: YWRtaW4= #value dari data
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA== #value dari data